### ISSUE TITLE
feat: dbt Weekly PyPI Refresh

### ISSUE THREAD

**Issue by TylerHillery** [TylerHillery/pypacktrends#49]
## Issue Description

Need to create weekly batch job that will run dbt to refresh any PyPI related tables and then sync that data to SQLite

## Tasks

- [ ] Created GitHub Action that is schedule weekly on monday at 02:00:00 or 03:00:00 UTC time.
  - [ ] Should also be able to manually run with passing in params for start date and end date. 
- [x] Figure out how to pass google auth from GitHub action to backend container to run sync.

**Comment by TylerHillery** [comment]
Resolved in #104
